name: my_camera_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0
  photo_manager: ^3.1.1
  path_provider: ^2.1.3
  path: ^1.9.0
  image_picker: ^1.1.1
  image: ^4.1.7

  flutter_localizations:
    sdk: flutter
  intl: any


flutter:
  uses-material-design: true
  generate: true
