name: my_camera_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0
  photo_manager: ^1.2.7
  path_provider: ^2.0.11
  path: ^1.8.1
  image_picker: ^1.1.1

  flutter_localizations:
    sdk: flutter
  intl: any
  image: ^4.1.7
  google_fonts: ^6.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
